version: "3.9"

services:
  server:
    build: .
    ports:
      - '8080:8080'

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
#      - my-db:/var/lib/mysql
      - ./src/main/resources/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: "/use/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 30s
      retries: 10

volumes:
  my-db: